#!/bin/sh
set -e
package_name=grub-btrfs-timeshift
mkdir -p "/usr/share/dpkgdivert/grub-btrfs-timeshift"
case "$1" in
  install)
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/grub-btrfs-timeshift/usrbintimeshift" --rename "/usr/bin/timeshift"
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/grub-btrfs-timeshift/usrbintimeshift-gtk" --rename "/usr/bin/timeshift-gtk"
    ;;
  upgrade)
if [ "$(dpkg-divert --list "/usr/bin/timeshift")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/grub-btrfs-timeshift/usrbintimeshift" --rename "/usr/bin/timeshift"
fi
if [ "$(dpkg-divert --list "/usr/bin/timeshift-gtk")" = "" ]
then
    dpkg-divert --package "$package_name" --divert "/usr/share/dpkgdivert/grub-btrfs-timeshift/usrbintimeshift-gtk" --rename "/usr/bin/timeshift-gtk"
fi
;;
esac
exit 0
